# Trigger on commits to the master branch, but only if the changes
# were in a location that affects the UPM package.
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Source/MSBuildTools.Unity/Packages

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  condition: and(not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/prerelease/')))
  inputs:
    filePath: 'AzurePipelines/Scripts/IncrementUPMVersion.ps1'
    arguments: '-IncrementPatch -PrereleaseID $(Build.BuildNumber)'
  displayName: 'Increment Version Patch Value (Non Release/Prerelease Branch)'

- task: PowerShell@2
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/prerelease/')
  inputs:
    filePath: 'AzurePipelines/Scripts/IncrementUPMVersion.ps1'
    arguments: '-PrereleaseID $(Build.BuildNumber)'
  displayName: 'Increment Version Patch Value (Non Release/Prerelease Branch)'

- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity'
    publishRegistry: 'useFeed'
    publishFeed: 'MSBuildForUnity/MSBuildForUnity'